### ISSUE TITLE
Proper install documentation effectively nonexistent. 

### ISSUE THREAD

**Issue by deefdragon** [bitnami/bitnami-docker-harbor-registry#2]
The current documentation for downloading and installing is lax at best, and has no descriptions of what values likely need to be changed. At a minimum it should inform the user to open the compose file and update the values listed as CHANGEME, the EXT_ENDPOINT, and how to enable it to work behind a web proxy. 

Also, a note on how the set the exact location of the registry volumes would be nice, give the size that these volumes could get to, and that someone may prefer to use the non-main drive for the images themselves.

**Comment by andresbono** [comment]
Hi @deefdragon, it is true that the documentation for this container repository is not very extensive. This is because it is usually used as a component for a complete harbor deployment. The full deployment is done with a Helm Chart.

Here you can find the Harbor Helm Chart: https://github.com/bitnami/charts/tree/master/bitnami/harbor and all the documentation that you may need to deploy it.

**Comment by deefdragon** [comment]
I would get the lack of documentation if it is expected to _only_ be deployed through helm. At that point I would be on my own. Currently however it is listed under the docker list on Bitnami, **and** you currently have the TLDR using docker-compose. 

If docker-compose isn't supported, or not the expected way to install it, then you may wish to denote that in the documentation, and not list it as the TLDR install method.

**Comment by andresbono** [comment]
You are right, @deefdragon. We should at least document the basic environment-variables that need to be changed. That documentation should go in https://github.com/bitnami/bitnami-docker-harbor-portal. The rest of the containers should point to harbor-portal README, in the same way the TL;DRs point to it.

I'm opening an internal task to improve this documentation. However, it may take some time for us to start working on it due to different priorities. It would be great if you contribute with a PR including the information that you would have expected to find. You can see other containers for reference and the Harbor chart as well:

- https://github.com/bitnami/bitnami-docker-wordpress#configuration
- https://github.com/bitnami/charts/tree/master/bitnami/harbor

**Comment by hemna** [comment]
I just deployed from the latest image, I edited the docker-compose.yml and changed all the CHANGME to a secret.  all the containers came up, but I can't login to the web portal with the REGISTRY_CREDENTIAL_USERNAME and REGISTRY_CREDENTIAL_PASSWORD values.  Not sure what to do.

**Comment by andresbono** [comment]
Hi @hemna, the password should be the value of `HARBOR_ADMIN_PASSWORD` in the harbor-core container. If you didn't change it, it should be `bitnami`.

https://github.com/bitnami/bitnami-docker-harbor-portal/blob/ca7ea6bb674096df7643c011cc178ac1dc79a297/2/debian-10/docker-compose.yml#L54

Please try with:
- username `admin`
- password `bitnami`

**Comment by hemna** [comment]
ok thank you that worked.   

FWIW, I also had to edit the docker-compose.yml and add ports to the registry container config to expose it to my system.
Also, it doesn't seem to generate/build a self signed cert, so https:// access to the registry doesn't work.  Need some documentation on how to add a self signed cert to the registry container.   Most systems now require https: even with a private registry.  :(

**Comment by andresbono** [comment]
I totally understand your point, @hemna. And for sure, we should create some basic documentation, I will try to increase the priority of our internal task. But please note that we highly recommend using our Helm Chart for production environments. For instance, it has the ability to configure https in all the services that support it.

**Comment by manuelnucci** [comment]
@hemna in which service did you expose the port? Can you show me an extract from your code?

**Comment by miguelaeh** [comment]
Hi @manuelnucci ,
If you are trying to access the UI in a single docker-compose, you should expose the harbor portal ports. I think this docker-compose should work to deploy all services: https://github.com/bitnami/bitnami-docker-harbor-portal/blob/master/docker-compose.yml

**Comment by manuelnucci** [comment]
This is the [file](https://gist.github.com/manuelnucci/b5e61a11f0e54409d6b6a93bca0b9537) I used to deploy Harbor and expose the port.

The NGINX volumes and ports where giving errors and conflicting with the port I wanted to expose from the portal.

**Comment by manuelnucci** [comment]
@andresbono the username/password provided does not seem to work, any ideas?

**Comment by manuelnucci** [comment]
Somehow following the instructions [here](https://github.com/bitnami/bitnami-docker-harbor-registry#tldr) didn't seem to work.

I had to execute the following commands and all the services started without any problem:

```
git clone https://github.com/bitnami/bitnami-docker-harbor-registry.git
cd bitnami-docker-harbor-portal/2/debian-10
docker-compose up -d
```

I think the command `curl -L https://github.com/bitnami/bitnami-docker-harbor-portal/archive/master.tar.gz | tar xz --strip=1 --wildcards '*-master/config'` is generating a wrong folder which breaks some services.

**Comment by miguelaeh** [comment]
Hi @manuelnucci ,
Honestly, I am not sure right now why that command is needed, but the docker-compose I shared should work without issues.

**Comment by Ming-Lyu** [comment]
docker-compose file not work as expected, No configuration file was detected, but my file is right under my config folder...lol

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
